import { Listing, SiteSettings } from '../src/types.ts';

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 1,
    category: 'STUDENT',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'حي المساعيد - بجوار بوابة الجامعة',
    title: 'شقة فاخرة مفروشة بالكامل 3 غرف - 5 دقائق من بوابة جامعة سيناء',
    price: 1800,
    rooms: 3,
    gender: 'بنين',
    distanceMin: 5,
    floor: 'الدور الثاني',
    area: '130 م²',
    address: 'شارع أسيوط الرئيسي، بجوار صيدلية النور، المساعيد',
    lat: 31.1315,
    lng: 33.8065,
    description: 'شقة طلابية راقية ومجهزة بالكامل للشباب، 3 غرف نوم واسعة بكل غرفة سريرين ومكتب للمذاكرة ودولاب. ريسبشن واسع بشاشة ذكية وتكييف، نت فايبر فائق السرعة، مطبخ مجهز بثلاجة وبوتاجاز وغسالة أوتوماتيك وسخان غاز، مياه متواصلة وعداد كهرباء كارت مستقل.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: true,
    hasWifi: true,
    hasFridge: true,
    hasWasher: true,
    hasKitchen: true,
    isFurnished: true,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: 6,
    bedsCount: 6,
    landlordPhone: '01550454849',
    views: 142,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    category: 'STUDENT',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'شارع البحر - المساعيد',
    title: 'سكن طالبات هادئ وآمن 2 غرفة - فيو بحر وقريب من مواصلات الجامعة',
    price: 1500,
    rooms: 2,
    gender: 'بنات',
    distanceMin: 8,
    floor: 'الدور الثالث (يوجد أسانسير)',
    area: '105 م²',
    address: 'كورنيش المساعيد، عمارة الأمل، مدخل خاص ومراقب بكاميرات',
    lat: 31.1352,
    lng: 33.7990,
    description: 'شقة خاصة مخصصة لطالبات كليات الصيدلة وطب الأسنان والهندسة، مدخل هادئ بحراسة 24 ساعة، عمودية على البحر مباشرة. فرش جديد بالكامل، إنترنت غير محدود سريع للمذاكرة، مطبخ متكامل، كل غرفة تحتوي على سرير ودولاب ومكتب خاص.',
    images: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: true,
    hasWifi: true,
    hasFridge: true,
    hasWasher: true,
    hasKitchen: true,
    isFurnished: true,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: 4,
    bedsCount: 4,
    landlordPhone: '01550454849',
    views: 218,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    category: 'STUDENT',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'خلف كلية العلوم والتكنولوجيا',
    title: 'استوديو مستقل سوبر لوكس للطلاب - 3 دقائق مشي لبوابة الجامعة',
    price: 1100,
    rooms: 1,
    gender: 'بنين',
    distanceMin: 3,
    floor: 'الدور الأرضي المرتفع',
    area: '55 م²',
    address: 'شارع الجامعة الجديد، خلف السور الجنوبي',
    lat: 31.1292,
    lng: 33.8041,
    description: 'استوديو ممتاز ومستقل مناسب لطالب أو طالبين يبحثان عن الهدوء والتركيز بالقرب الشديد من قاعات المحاضرات. غرفة كبيرة مع حمام خاص ومطبخ أمريكي صغير وتكييف موفر للطاقة وشبكة نت ممتازة.',
    images: [
      'https://images.unsplash.com/photo-1502005229762-ee1b2b93e007?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'RESERVED',
    hasAc: true,
    hasWifi: true,
    hasFridge: true,
    hasWasher: false,
    hasKitchen: true,
    isFurnished: true,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: 2,
    bedsCount: 2,
    landlordPhone: '01550454849',
    views: 310,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    category: 'STUDENT',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'شارع الزهور - المساعيد',
    title: 'شقة فندقية طالبات 3 غرف ماستر - مكيفة بالكامل مع خدمات أسبوعية',
    price: 2400,
    rooms: 3,
    gender: 'بنات',
    distanceMin: 6,
    floor: 'الدور الأول',
    area: '140 م²',
    address: 'ميدان الزهور، بالقرب من كافيهات ومطاعم الطلاب',
    lat: 31.1328,
    lng: 33.8080,
    description: 'شقة فندقية عالية الجودة لطالبات الكليات الطبية والهندسية. كل غرفة بحمام منفصل أو خاص، تكييفات كاريير في كل الغرف، مطبخ مجهز بفرن وميكروويف وغسالة أوتوماتيك وثلاجة كبيرة، شاشة تلفزيون ونظام أمان متكامل.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'RENTED',
    hasAc: true,
    hasWifi: true,
    hasFridge: true,
    hasWasher: true,
    hasKitchen: true,
    isFurnished: true,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: 5,
    bedsCount: 5,
    landlordPhone: '01550454849',
    views: 420,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    category: 'STUDENT',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'منطقة الروضة الجديدة',
    title: 'شقة اقتصادية نظيفة للشباب 2 غرفة - قريبة من خط أتوبيسات الجامعة',
    price: 950,
    rooms: 2,
    gender: 'بنين',
    distanceMin: 12,
    floor: 'الدور الرابع',
    area: '90 م²',
    address: 'تقاطع شارع الفاتح مع شارع الروضة، أمام مجمع الخدمات',
    lat: 31.1240,
    lng: 33.8115,
    description: 'شقة اقتصادية تناسب 4 طلاب بأسعار مناسبة جداً مع الحفاظ على مستوى النظافة والراحة. تحتوي على غرفتين مجهزتين بأسرة ومكاتب، مطبخ وحمام وغسالة نصف أوتوماتيك ونت سريع ومياه متوفرة بخزان مستقل.',
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: false,
    hasWifi: true,
    hasFridge: true,
    hasWasher: true,
    hasKitchen: true,
    isFurnished: true,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: 4,
    bedsCount: 4,
    landlordPhone: '01550454849',
    views: 95,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // LOCAL / EL-BALAD PROPERTIES
  {
    id: 6,
    category: 'LOCAL',
    propertyType: 'RENT_APARTMENT',
    neighborhood: 'وسط البلد - شارع 23 يوليو',
    title: 'شقة عائلية سوبر لوكس 3 غرف وصالة للإيجار الشهري - موقع حيوي',
    price: 3500,
    rooms: 3,
    gender: 'عائلي',
    distanceMin: 20,
    floor: 'الدور الثاني',
    area: '160 م²',
    address: 'شارع 23 يوليو الرئيسي، بجوار البنك الأهلي المصري',
    lat: 31.1340,
    lng: 33.7910,
    description: 'شقة سكن عائلي ممتازة تشطيب الترا سوبر لوكس، سيراميك كليوباترا، دهانات جوتن، ريسبشن 3 قطع، 3 غرف نوم مريحة، 2 حمام، مطبخ كبير جاهز. موقع راقي جداً وسط الخدمات والمدارس والمستشفيات.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: true,
    hasWifi: false,
    hasFridge: false,
    hasWasher: false,
    hasKitchen: true,
    isFurnished: false,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: null,
    bedsCount: null,
    landlordPhone: '01550454849',
    views: 184,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    category: 'LOCAL',
    propertyType: 'SALE',
    neighborhood: 'حي الكرامة - الفيلات',
    title: 'شقة تمليك 180م² بحري ناصية صريحة للبيع كاش أو بتسهيلات',
    price: 850000,
    rooms: 4,
    gender: 'عائلي',
    distanceMin: 25,
    floor: 'الدور الثالث',
    area: '180 م²',
    address: 'شارع الفيلات، حي الكرامة الجديد، عمارة حديثة الإنشاء',
    lat: 31.1210,
    lng: 33.7840,
    description: 'فرصة استثمارية وسكنية مميزة: شقة تمليك 180 متر مربع ناصية بحري مفتوحة غير مجروحة نهائياً. عمارة حديثة واجهة حجر هاشمي وأسانسير إيطالي ومدخل رخام فاخر. 3 غرف نوم + غرفة معيشة + ريسبشن كبير و3 تراس. حصة في الأرض مسجلة.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: false,
    hasWifi: false,
    hasFridge: false,
    hasWasher: false,
    hasKitchen: true,
    isFurnished: false,
    hasWaterHeater: false,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: null,
    bedsCount: null,
    landlordPhone: '01550454849',
    views: 290,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    category: 'LOCAL',
    propertyType: 'COMMERCIAL',
    neighborhood: 'شارع التجاري الرئيسي',
    title: 'محل تجاري 70م² دور أرضي واجهة زجاجية بموقع حيوي - للإيجار',
    price: 5000,
    rooms: 1,
    gender: 'مختلط',
    distanceMin: 18,
    floor: 'الدور الأرضي',
    area: '70 م²',
    address: 'شارع التجاري المتفرع من شارع البحر، بالقرب من مجمع العيادات',
    lat: 31.1310,
    lng: 33.7950,
    description: 'محل تجاري مميز جداً يصلح لكافة الأنشطة (صيدلية، كافيه، مكتب توكيلات، معرض ملابس، سوبر ماركت). واجهة زجاجية بطول 6 أمتار على الشارع الرئيسي مع مطلع بضائع وعداد كهرباء تجاري 3 فاز ومياه وحمام داخلي.',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: true,
    hasWifi: false,
    hasFridge: false,
    hasWasher: false,
    hasKitchen: false,
    isFurnished: false,
    hasWaterHeater: true,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: null,
    bedsCount: null,
    landlordPhone: '01550454849',
    views: 175,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    category: 'LOCAL',
    propertyType: 'LAND',
    neighborhood: 'تقسيم النخيل الجديد',
    title: 'قطعة أرض 300م² مباني مسجلة كاملة المرافق - للبيع السريع',
    price: 600000,
    rooms: 0,
    gender: 'عائلي',
    distanceMin: 30,
    floor: 'أرض فضاء',
    area: '300 م²',
    address: 'تقسيم النخيل المعتمد، رخصة بناء أرضي و4 أدوار',
    lat: 31.1180,
    lng: 33.7750,
    description: 'قطعة أرض ممتازة للبناء السكني، أبعاد 15م × 20م على شارع 12 متر. كردون مباني ورخصة جاهزة، واصل لها مياه وكهرباء وغاز طبيعي. عقد أزرق خالص الثمن ومسجلة شهر عقاري بدون أي توكيلات أو نزاعات.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80'
    ],
    whatsapp: '201550454849',
    status: 'AVAILABLE',
    hasAc: false,
    hasWifi: false,
    hasFridge: false,
    hasWasher: false,
    hasKitchen: false,
    isFurnished: false,
    hasWaterHeater: false,
    hasElectricity: true,
    hasWater: true,
    capacityStudents: null,
    bedsCount: null,
    landlordPhone: '01550454849',
    views: 89,
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteName: 'أركان للتسويق العقاري',
  siteSlogan: 'غيّرنا شكل السمسرة',
  logoUrl: '/logo.png',
  logoLetter: 'A',
  commissionBadge: '0% عمولة',
  pricingModelText: '30 جنيه فقط للمُعلن • 0% من المستأجر',
  heroNotice: 'أول منصة رقمية متخصصة لسكن طلاب جامعة سيناء وعقارات العريش بدون سماسرة',
  phone: '01550454849',
  whatsappNumber: '201550454849',
  whatsappWelcomeMsg: 'السلام عليكم، حابب أعرض عقاري مع أركان للتسويق العقاري بميزة الـ 30 جنيه فقط و 0% عمولة.',
  facebookUrl: 'https://www.facebook.com/share/17e8UBzfbi/',
  instagramUrl: 'https://www.instagram.com/arkan_real_estate?stkn=MWhqc21nbm1pZnZkMw==',
  tiktokUrl: 'https://www.tiktok.com/@arkan_real_estate?_r=1&_t=ZS-99YaNTroP3K',
  footerDesc: 'المنصة المتخصصة الأولى لسكن طلاب جامعة سيناء بالعريش، وعقارات البلد للأهالي والسكان المحليين. تعامل مباشر وبدون وسيط.',
  copyrightText: 'أركان للتسويق العقاري (Arkan Real Estate Marketing). جميع الحقوق محفوظة.',
  aboutTitle: 'لماذا أسسنا "أركان"؟',
  aboutText: 'تأسست أركان للتسويق العقاري كأول منصة رقمية متخصصة تجمع بين السكن الطلابي لجامعة سيناء بالعريش وسوق العقارات المحلي في البلد. هدفنا التخلص تمامًا من أسلوب السمسرة التقليدي والعمولات الباهظة التي تثقل كاهل الطلاب والأهالي.',
  aboutPoints: [
    { title: 'عمولة صفر على المستأجر', desc: 'الطالب أو المستأجر لا يدفع أي عمولة أو رسوم معاينة نهائيًا.', badge: '0%' },
    { title: '30 جنيه فقط للمالك', desc: 'رسم رمزي ثابت للمالك أو المُعلن لعرض شقته وتسويقها حتى يتم تأجيرها.', badge: '30 ج' },
    { title: 'عقود وإجراءات موثوقة', desc: 'تواصل وتنسيق مباشر بين الطرفين بشفافية كاملة وصور حقيقية.', badge: 'موثق' },
    { title: 'تغطية شاملة للمدينة والبلد', desc: 'سكن طلاب قريب من كليات جامعة سيناء + شقق عائلية وأراضي وتجاري.', badge: 'شامل' }
  ],
  mapCenterLat: 31.1340,
  mapCenterLng: 33.8055,
  mapDefaultZoom: 15,
  universityGateName: 'بوابة جامعة سيناء الرئيسية',
  universityGateNote: 'نقطة قياس مسافات السكن الطلابي',
  mapLandmarks: [
    {
      id: 'uni-gate-main',
      name: 'بوابة جامعة سيناء الرئيسية',
      category: 'university',
      note: 'البوابة الشمالية أمام كليات الصيدلة وطب الأسنان والعلوم',
      lat: 31.1340,
      lng: 33.8055,
      icon: '🎓'
    },
    {
      id: 'student-parking',
      name: 'موقف سيارات وميكروباص الطلاب',
      category: 'transport',
      note: 'موقف الانتقالات الداخلي وسيارات المساعيد والمحافظات',
      lat: 31.1332,
      lng: 33.8042,
      icon: '🚌'
    },
    {
      id: 'baraka-market',
      name: 'هايبر ماركت البركة',
      category: 'market',
      note: 'أكبر مركز تسوق غذائي قريب من سكن الطلاب',
      lat: 31.1355,
      lng: 33.8080,
      icon: '🛒'
    },
    {
      id: 'nour-pharmacy',
      name: 'صيدلية النور (24 ساعة)',
      category: 'hospital',
      note: 'خدمة 24/7 مع توصيل سريع للسكن الجامعي',
      lat: 31.1325,
      lng: 33.8070,
      icon: '💊'
    },
    {
      id: 'masaeed-beach',
      name: 'كورنيش وشاطئ المساعيد',
      category: 'beach',
      note: 'متنزه ترفيهي وكافيهات مطلة على البحر للطلاب',
      lat: 31.1410,
      lng: 33.8020,
      icon: '🌊'
    }
  ],
  transportHeaderTitle: 'الخدمات القريبة من جامعة سيناء',
  transportHeaderSubtitle: 'كل ما تحتاجه يومياً حول محيط سكنك الجامعي وقاعات المحاضرات',
  transportCategories: [
    {
      id: 'transport',
      icon: 'bus',
      title: 'مواصلات الجامعة والخطوط',
      badge: 'بوابات ومواقف',
      places: [
        { name: 'موقف ميكروباص الجامعة الرئيسي', note: 'أمام البوابة الشمالية لكليات العلوم والصيدلة', distance: '1 دقيقة' },
        { name: 'خط المساعيد - الجامعة الداخلي', note: 'متاح كل 5 دقائق على مدار اليوم', distance: 'مباشر' },
        { name: 'أتوبيسات نقل الطلاب للمحافظات', note: 'موقف الأمل يومي الخميس والجمعة', distance: '8 دقائق' }
      ]
    },
    {
      id: 'markets',
      icon: 'shopping-cart',
      title: 'سوبر ماركت وبقالة',
      badge: 'احتياجات يومية',
      places: [
        { name: 'هايبر ماركت البركة', note: 'توصيل مجاني لسكن الطلاب حتى 2 صباحاً', distance: '3 دقائق' },
        { name: 'ماركت المدينة الطلابية', note: 'أجبان، مأكولات سريعة، مستلزمات دراسية', distance: '5 دقائق' },
        { name: 'سوبر ماركت أولاد رجب الفرع الجديد', note: 'خضار وفواكه طازجة ولحوم', distance: '7 دقائق' }
      ]
    },
    {
      id: 'pharmacies',
      icon: 'pill',
      title: 'صيدليات وخدمات طبية',
      badge: 'طوارئ 24/7',
      places: [
        { name: 'صيدلية النور (خدمة 24 ساعة)', note: 'شارع أسيوط، خصم خاص لطلاب جامعة سيناء', distance: '4 دقائق' },
        { name: 'صيدلية الشفاء التخصصية', note: 'توصيل سريع للسكن والأدوية المستوردة', distance: '6 دقائق' },
        { name: 'مجمع العيادات التخصصي الخيري', note: 'كشف واستشارات طبية بأسعار رمزية للطلاب', distance: '9 دقائق' }
      ]
    },
    {
      id: 'restaurants',
      icon: 'utensils',
      title: 'مطاعم وكافيهات للمذاكرة',
      badge: 'وجبات وواي فاي',
      places: [
        { name: 'كافيه سنترال ستيودنت (Student Zone)', note: 'أماكن هادئة للمذاكرة، نت فايبر سريع، مشروبات', distance: '3 دقائق' },
        { name: 'مطعم حضرموت سيناء للوجبات', note: 'وجبات غداء اقتصادية خاصة بالطلبة', distance: '5 دقائق' },
        { name: 'شاورما وجريل الشام', note: 'سندوتشات سريعة ودليفري حتى الفجر', distance: '4 دقائق' }
      ]
    },
    {
      id: 'laundry',
      icon: 'shirt',
      title: 'مغاسل ودراي كلين',
      badge: 'تنظيف وكي',
      places: [
        { name: 'مغسلة الأمانة السريعة للطلاب', note: 'غسيل وكي ملابس السكن مع الاستلام والتوصيل', distance: '4 دقائق' },
        { name: 'دراي كلين النجوم بالمساعيد', note: 'تنظيف البطاطين والمفروشات بالبخار', distance: '6 دقائق' },
        { name: 'مغسلة إكسبريس الحديثة', note: 'خدمة تسليم خلال 3 ساعات', distance: '7 دقائق' }
      ]
    }
  ]
};

